// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//
// Fuzz target for WTA's commandline builder.
//
// This exercises build_wt_commandline with arbitrary (command, args) pairs
// generated by the Arbitrary trait, looking for panics and correctness
// violations in the quoting/escaping logic.

#![no_main]

use arbitrary::Arbitrary;
use libfuzzer_sys::fuzz_target;
use wta::build_wt_commandline;

/// Structured fuzz input: a command string and a list of arguments.
#[derive(Arbitrary, Debug)]
struct FuzzInput {
    command: String,
    args: Vec<String>,
}

fuzz_target!(|input: FuzzInput| {
    // Skip degenerate inputs that would make the test noisy
    if input.command.is_empty() {
        return;
    }
    if input.args.len() > 64 {
        return;
    }

    let result = build_wt_commandline(&input.command, &input.args);

    // Basic sanity checks — these catch escaping failures:

    // 1. The result must start with the command
    assert!(
        result.starts_with(&input.command),
        "Commandline doesn't start with command: {:?} -> {:?}",
        input.command,
        result
    );

    // 2. The result must not be empty if the command is non-empty
    assert!(!result.is_empty());

    // 3. No null bytes should appear (would truncate the commandline)
    if !input.command.contains('\0') && !input.args.iter().any(|a| a.contains('\0')) {
        assert!(
            !result.contains('\0'),
            "Null byte injected into commandline: {:?}",
            result
        );
    }
});
